name: Update News JSON

on:
  schedule:
    - cron: "0 17 * * *"  # 매일 한국시간 02:00 실행 (UTC 17:00)
  workflow_dispatch:  # ✅ 이 줄을 추가하면 Run workflow 버튼 생성됨

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3

    - name: Python 설치
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Python 패키지 설치
      run: |
        pip install yahooquery
        pip install feedparser

    - name: Python 스크립트 실행 (news.json 업데이트)
      run: python update_news.py

    - name: 변경 사항 커밋 & 푸시
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add news.json
        git commit -m "자동 업데이트: 뉴스 데이터 최신화"
        git push
      continue-on-error: true